lifecycle:
  preStop:
    enabled: false

helmHooks:
  enabled: false
  
elasticsearchHosts: "https://elasticsearch-master:9200"

elasticsearchUsername: elastic
elasticsearchPassword: "hUqrknjN2OESRRuB"

resources:
  requests:
    cpu: "200m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"

service:
  type: LoadBalancer
